config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  begin
    ActiveAdmin.routes(self)
  rescue Exception => e
    puts "ActiveAdmin: #{e.class}: #{e}"
  end

 
  get 'pages/home',           to:"pages#index",          as: :home
  get 'pages/meia_entrada',   to:"pages#meia_entrada",   as: :meia_entrada
  get 'pages/noticias',       to:"pages#noticias",       as: :noticias
  get 'pages/consulta',       to:"pages#consulta",       as: :consulta
  get 'pages/contato',        to:"pages#contato",        as: :contato
  get 'pages/login',          to:"pages#login",          as: :login

  resources :estudantes, only: [:show, :update] do 
    resources :carteirinhas, only: [:new, :show, :autenticacao, :create]
  end
  
  post 'estudantes/senha',   to:"estudantes#update_password", as: :alterar_password
  get 'entidades/escolaridades', to:"entidades#escolaridades"
  get 'entidades/cursos', to:"entidades#cursos"

  resources :contatos, only:[:create]

  devise_for :estudantes, path: "auth", controllers: {:omniauth_callbacks=>"estudantes/omniauth_callbacks"},
                          path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', 
                                                                confirmation: 'verification', unlock: 'unblock', 
                                                                registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :escolaridades, only: [:show] do
    resource :cursos, only: [:show]
  end

  get 'carteirinhas/status', to: "carteirinhas#status_versao_impressas"

  resources :estados, only: [:show] do
    resource :cidades, only: [:show]
  end

  get 'payment/checkout',          to:'checkout#create',        as: :checkout
  get 'payment/confirmacao',      to:'checkout#confirmacao'
  post 'payment/notifications',    to:'notifications#create'
  
  get 'carteirinhas/image', to:'carteirinhas#carteirinha_image'
  post 'carteirinhas/consulta',   to:"carteirinhas#consulta", as: :consulta_carteirinha

  get 'certificados/:chave_acesso', to:"certificados#show" # Não alterar

  resources :eventos, only: [:show]

  namespace :api, defaults:{format: :json} do
    resources :estudantes, only: [:update], param: :oauth_token do
      resources :carteirinhas, only: [:create, :show]
    end
    get 'carteirinhas',          to: 'carteirinhas#index'
    get 'sessions/new',          to: 'sessions#create'   
    get 'sessions/new/facebook', to: 'sessions#facebook'
    post 'registration',         to: 'registrations#create' 
    resources :noticias, only:[:index]

    post 'certificados/create', to:'certificados#create'  # cria certificados
  
    get 'estudantes/:id/attachments/:name', to: 'attachments#show' 
    put 'estudantes/:id/attachments/update/:name', to: 'attachments#update'
  end

  root 'pages#index'

end

app/models/carteirinha.rb
class Carteirinha < ActiveRecord::Base

	belongs_to :estudante
	belongs_to :entidade
	belongs_to :layout_carteirinha
	belongs_to :admin_user

	url_path = "/default/:class/:id/:attachment/:style/:filename"

	has_attached_file :foto, :styles => {:original => {}}, :path => "#{url_path}"
	has_attached_file :xerox_cpf, :styles => {:original => {}}, :path => "#{url_path}"
	has_attached_file :xerox_rg, :styles => {:original => {}}, :path => "#{url_path}"
	has_attached_file :comprovante_matricula, :styles => {:original => {}}, :path => "#{url_path}"

	FILES_NAME_PERMIT = [/png\Z/, /jpe?g\Z/, /pdf\Z/]
	FILES_CONTENT_TYPE = ['image/jpeg', 'image/png', 'application/pdf']

	EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/
	STRING_REGEX = /\A[a-z A-Z]+\z/
	LETRAS = /[A-Z a-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ ]+/

	@@status_versao_impressas = {pagamento: "Pagamento", documentacao: "Documentação", aprovada: "Aprovada", 
								   					   enviada: "Enviada", entregue: "Entregue", cancelada: "Cancelada", revogada: "Revogada"}

	@@forma_pagamentos = {cartao_de_credito: "Cartão de crédito", boleto: "Boleto", a_definir: "A definir",
										    debito_online: "Débito online", saldo_pagseguro: "Saldo PagSeguro", 
										    oi_pago: "Oi Paggo", deposito_em_conta: "Depósito em conta", dinheiro: "Dinheiro"}		   				

	@@status_pagamentos = {iniciado: "Iniciado", aguardando_pagamento: "Aguardando pagamento", em_analise: "Em análise",
							 				   pago: "Pago", disponivel: "Disponível", em_disputa: "Em disputa", devolvido: "Devolvido",
							 				   cancelado: "Cancelado", contestado: "Contestado"}

	enum status_versao_impressa: @@status_versao_impressas
	enum forma_pagamento: @@forma_pagamentos
	enum status_pagamento: @@status_pagamentos

	# validações
	validates :nome, length: { maximum: 70, too_long: "Máximo de 70 caracteres permitidos"}, format:{with: LETRAS, message:"Somente letras é permitido!"}
	validates :instituicao_ensino, length:{maximum: 50}
	validates :curso_serie, length:{maximum: 70}
	validates :matricula, numericality: true, length:{maximum: 30}, allow_blank: true
	validates :rg, numericality: {only_integer: true}
	validates :instituicao_ensino, length:{maximum: 50, too_long: "Máximo de 50 caracteres permitidos!."}, format: {with: LETRAS}, allow_blank: true
	validates :cidade_inst_ensino, length:{maximum: 30, too_long:"Máximo de 70 carectetes é permitidos!"}, format:{with: LETRAS}, allow_blank: true
	validates :curso_serie, length:{maximum: 40, too_long: "Máximo de 40 caracteres permitidos!."}, format:{with: LETRAS}, allow_blank: true
	validates :termos, acceptance: true
	validates :numero_serie, numericality: true, uniqueness: true, allow_blank: true
	validates :cpf, numericality: true, length:{is: 11, too_long: "Necessário 11 caracteres.",  too_short: "Necessário 11 caracteres."}, allow_blank: true
	validates :expedidor_rg, length:{maximum: 10, too_long:"Máximo de 10 caracteres permitidos!"}, 
							 						 format:{with:STRING_REGEX, message: "Somente letras é permitido!"}, allow_blank: true
	validates :uf_expedidor_rg, length:{is: 2}, format:{with:STRING_REGEX}, allow_blank: true
	validates :uf_inst_ensino, length:{is: 2}, format:{with:STRING_REGEX}, allow_blank: true
	validates :escolaridade, length:{maximum: 30, too_long: "Máximo de 30 caracteres permitidos!"},
							             format:{with:LETRAS, message:"Somente letras é permitido"}, allow_blank: true
	#foto
	validates_attachment_size :foto, :less_than => 1.megabytes
	validates_attachment_file_name :foto, :matches => [/png\Z/, /jpe?g\Z/]
	validates_attachment_content_type :foto, :content_type => ['image/jpeg', 'image/png', 'application/pdf']
	#xerox_rg
	validates_attachment_size :xerox_rg, :less_than => 1.megabytes
	validates_attachment_file_name :xerox_rg, :matches => FILES_NAME_PERMIT
	validates_attachment_content_type :xerox_rg, :content_type => FILES_CONTENT_TYPE
	#xerox_cpf
	validates_attachment_size :xerox_cpf, :less_than => 1.megabytes
	validates_attachment_file_name :xerox_cpf, :matches => FILES_NAME_PERMIT
	validates_attachment_content_type :xerox_cpf, :content_type => FILES_CONTENT_TYPE
	#comprovante_matricula
	validates_attachment_size :comprovante_matricula, :less_than => 1.megabytes
	validates_attachment_file_name :comprovante_matricula, :matches => FILES_NAME_PERMIT
	validates_attachment_content_type :comprovante_matricula, :content_type => FILES_CONTENT_TYPE

	validates_presence_of :estudante

	validate :so_muda_status_versao_impressa_se_pagamento_confirmado, :nao_avancar_status_se_dados_em_branco,
			 :check_status_carteirinha_apartir_status_pagamento

	before_update :gera_dados_se_carteirinha_aprovada, :muda_status_carteirinha_apartir_status_pagamento

	def dias_validade 
		nao_depois  = self.nao_depois
		seconds = nil
		dias = nil
		if nao_depois 
			seconds = self[:nao_depois] - Time.now.to_date
			dias = seconds*1000/24*60*60
		else
			dias = 1000;
		end
		dias.days
	end

	def valid
		dias_validade >= 0
	end

	def em_solicitacao?
		if valid
			if self.status_versao_impressa.aprovada?
				return false
			else
				return true
			end
		else
			return false
		end
	end

	def status_tag_versao_impressa
		status=""
		if self.status_versao_impressa_to_i <= 1
			status = :warning
		elsif self.status_versao_impressa_to_i >= 2 && self.status_versao_impressa_to_i <= 4 
			status = :ok
		elsif self.status_versao_impressa_to_i > 4 
			status = :error
		end
		status
	end

	def status_tag_status_pagamento
		status=""
		status_pgto_to_i = self.status_pagamento_to_i
		if status_pgto_to_i <= 2 
			status = :warning
		elsif status_pgto_to_i > 2 && status_pgto_to_i <= 4 
			status = :ok
		else status_pgto_to_i > 4 
			status = :error
		end
		status
	end

	def status_take_while
		index = self.status_versao_impressa_to_i+1
		statuses = @@status_versao_impressas.map{|k,v| v}
		statuses.take index
	end

	def solicitacao_cancelada_ou_revogada?
		self.status_versao_impressa == :cancelada || self.status_versao_impressa == :revogada
	end

	def so_muda_status_versao_impressa_se_pagamento_confirmado
		if self.status_pagamento_to_i < 3 # pagamento nao confirmado
			 errors.add(:status_versao_impressa, "pagamento da CIE não foi realizado") if status_versao_impressa_to_i >= 1
		end
	end

	def check_status_carteirinha_apartir_status_pagamento
		status_carteirinha = Carteirinha.show_status_carteirinha_apartir_do_status_pagamento self.status_pagamento
		status_carteirinha = status_carteirinha.map{|k,v| k}
		index = status_carteirinha.index(self.status_versao_impressa.to_sym)
		errors.add(:status_versao_impressa, "valor inválido para dado Status de Pagamento: #{self.status_pagamento.humanize} ") unless index
	end

	def nao_avancar_status_se_dados_em_branco
		if self.status_versao_impressa_to_i == 3 || self.status_versao_impressa_to_i == 4 # ENVIADA OU ENTREGUE
            variavel = [:nao_antes, :nao_depois, :codigo_uso, :qr_code, :certificado, 
            	        :numero_serie, :layout_carteirinha_id, :estudante_id]
            variavel.each do |v|
            	errors.add(v, "não pode ficar em branco") if self[v].blank? || self[v].nil?
            end
        end
	end

	def status_versao_impressa_to_i
		index=-1
		i=0
		@@status_versao_impressas.each_key do |key|
			index=i if key == self.status_versao_impressa.to_sym
			i=i+1
		end
		index
	end

	def status_pagamento_to_i
		Carteirinha.status_pagamento_to_i(self.status_pagamento)
	end

	def muda_status_carteirinha_apartir_status_pagamento
		#em processamento
		self.status_versao_impressa = :pagamento if status_pagamento_to_i <= 2
	end

	def self.status_pagamento_to_i status_pgto
		statuses = @@status_pagamentos.map{|k,v| k}
		statuses.index(status_pgto.to_sym)
	end

	def self.status_pagamento_by_code code
 		statuses = Carteirinha.status_pagamentos.map{|k,v| k}
 		if 1 < code.to_i && code.to_i < 7
 			return statuses[code.to_i]
 		else
 			return statuses[0] # Iniciado
 		end
 	end

	def self.forma_pagamento_by_type type
		formas = Carteirinha.forma_pagamentos.map{|k,v| k}
		forma = ''
		case type
		when "1" then forma = formas[0] # Cartão de Crédito
		when "2" then forma = formas[1] # Boleto
		when "3" then forma = formas[3] # Débito on-line
		when "4" then forma = formas[4] # Saldo Pag-seguro
		when "5" then forma = formas[5] # Oi pago
		when "7" then forma = formas[6] # Depósito em conta
		else forma = formas[2] # a definir
		end
		forma 
	end

	def self.show_status_carteirinha_apartir_do_status_pagamento status_pgto
		# Calcula status_pagamento_to_i
		status_pgto_to_i = Carteirinha.status_pagamento_to_i status_pgto
		status=[]
		if status_pgto_to_i <= 2  # iniciada, aguardando_pagamento, em_analise
			status = @@status_versao_impressas.select{|k,v| k == :pagamento} # somente pagamento 
		elsif status_pgto_to_i >=3 && status_pgto_to_i <= 4 # paga , disponível
			status = @@status_versao_impressas.select{|k,v| k != :pagamento} #todas as opções de status_versao impressa
		elsif status_pgto_to_i == 5 # em disputa
			status = @@status_versao_impressas.select{|k,v| k != :aprovada}
		elsif status_pgto_to_i > 5  # devolvida cancelada ou revogada
			status = @@status_versao_impressas.select{|k,v| k == :cancelada || k == :revogada || k == :devolvida} 
		end
		status
	end

	def gera_dados_se_carteirinha_aprovada
		if self.aprovada? # Status é 'Aprovada'
            # Gera informações  
            estudante = self.estudante
            self.layout_carteirinha = estudante.entidade.layout_carteirinhas.first        if self.layout_carteirinha.blank?
            self.nao_antes = Time.new                                                     if self.nao_antes.blank?
            self.nao_depois = Time.new(Time.new.year+1, 3, 31).to_date                    if self.nao_depois.blank? 
            self.numero_serie = Carteirinha.gera_numero_serie                             if self.numero_serie.blank?
            self.codigo_uso = Carteirinha.gera_codigo_uso                                 if self.codigo_uso.blank?

app/controllers/api/carteirinhas_controller.rb
class Api::CarteirinhasController < Api::AuthenticateBase

	before_action :http_base_authentication_with_entidade_data, only: [:index]
	before_action :http_token_authentication, only: [:show, :create]

	def index
		status = Carteirinha.status_versao_impressa[2]
		@carteirinhas = Carteirinha.where("status_versao_impressa = ? AND certificado = ?", status, "")
		if @carteirinhas.empty?
			render_erro "Nenhuma Carteira de Identificação Estudantil com status #{status} encontrada.", 404
		else
			entidade = Entidade.instance
			if entidade.nil?
				render_erro "Nenhuma entidade encontrada.", 404
			else
				if entidade.auth_info_access.blank? || entidade.crl_dist_points.blank?
					render_erro "'Autoridade de Acesso à Informação' e/ou 'CRL Ponto de Distribuição' não estão preenchidos.", 500 
				else
					json = {:entidade => {:auth_info_access => entidade.auth_info_access, 
										  :crl_dist_points => entidade.crl_dist_points, 
					        			  :carteirinhas => @carteirinhas.map{|c| CarteirinhaSerializer.new(c)}}}
					respond_with json
				end
			end
		end
	end

	def show
		begin
			@estudante = Estudante.find_by_oauth_token(params[:estudante_oauth_token])
			if @estudante
				if @estudante.carteirinha.empty?
		    	render_erro "Nenhuma Carteira de Identificação Estudantil encontrada.", 404
		    else
		    	respond_with @estudante.carteirinha.last, :status => 200
		    end
		  else
		  	render_erro "Estudante não encontrado, oauth_token: #{params[:estudante_oauth_token]}", 404
		  end
		rescue Exception => ex
			render_erro ex.message, 500
		end
	end

	def create
		begin 
			@estudante = Estudante.find_by_oauth_token(params[:estudante_oauth_token])
			if @estudante
				if @estudante.atributos_em_branco.empty?
					@carteirinhas = @estudante.carteirinha
					if @carteirinhas && @carteirinhas.last && @carteirinhas.last.em_solicitacao?
						@last_carteirinha = @carteirinhas.last
						message = "Carteira de Identificação Estudantil já solicitada"
						render json: {erros: message, status_versao_impressa: @last_carteirinha.status_versao_impressa,
							            type: 'erro'}, :status => 422
					else
						nova_carteirinha = @estudante.carteirinha.new(carteirinha_params) do |c|
							c.nome = @estudante.nome
							c.instituicao_ensino = @estudante.instituicao_ensino
							c.curso_serie = @estudante.curso_serie
							c.matricula = @estudante.matricula
							c.rg_certidao = @estudante.rg_certidao
							c.data_nascimento = @estudante.data_nascimento
							c.cpf = @estudante.cpf
							c.foto = @estudante.foto
						end	
						if nova_carteirinha.save
							# Metodo que envia boleto aqui
							respond_with nova_carteirinha, :status => 201
						else
							render json: {errors: nova_carteirinha.errors, type: 'erro'}, :status => 422
						end
					end
				else
					atributos_em_branco = @estudante.atributos_em_branco.to_s
					render_erro "Dados não preenchidos: #{atributos_em_branco}", 422
				end
			else
				render_erro "Estudante não encontrado, oauth_token: #{params[:estudante_oauth_token]}", 404
			end
		rescue => ex
			render_erro ex.message, 500
		end
	end

	private 
		def carteirinha_params
			params.require(:carteirinha).permit(:valor, :status_versao_impressa)
		end
end

app/controllers/carteirinhas_controller.rb
class CarteirinhasController < ApplicationController

	before_action :authenticate_estudante!, 
								except: [:consulta, :show, :carteirinha_image, :status_versao_impressas]

	def show
		
	end

	def carteirinha_image
		@carteirinha = Carteirinha.find(params[:id])
		send_data @carteirinha.to_blob, :type=>"image/jpg", :disposition=>"inline"
	end

	def new
		
	end

	def create 
		atributos = current_estudante.atributos_nao_preenchidos
		if atributos.count > 0
			campos = ""
			atributos.collect{|f| campos.concat(f.to_s.humanize.concat(", "))}
			flash[:alert] = "Campo(s) #{campos} não preenchido(s)."
			redirect_to estudante_path(current_estudante)
		else
			if carteirinha_params[:termos] == "0"
				flash[:alert] = "Os Termos de Serviço devem ser aceitos."
				redirect_to estudante_path(current_estudante)
			else
				redirect_to checkout_path(valor_carteirinha: carteirinha_params[:valor_carteirinha], frete_carteirinha: carteirinha_params[:frete_carteirinha])
			end	
		end
	end

	def consulta		
		@carteirinha = Carteirinha.find_by_codigo_uso(params[:carteirinha][:codigo_uso])
		if verify_recaptcha(model: @carteirinha)
			respond_to do |format|
				format.html{redirect_to consulta_url}
				format.js
			end
		else
		  redirect_to consulta_url
		end			
	end

	def status_versao_impressas
		@statuses = 
		Carteirinha.show_status_carteirinha_apartir_do_status_pagamento params[:status_pagamento]
		respond_to do |format|
			format.js
		end
	end

	private
		def carteirinha_params
			params.require(:carteirinha).permit(:valor_carteirinha, :termos, :frete_carteirinha, :status_pagamento)
		end
end

app/helpers/carteirinhas_helper.rb
module CarteirinhasHelper
end

app/views/carteirinhas/_carteirinha.html.erb
<%= image_tag url_for(:action => 'carteirinha_image', :id => @carteirinha.id)  %>

app/views/carteirinhas/_historico.html.erb
<h4 class="text-primary"> Histórico de Solicitações </h4>
	<% @carteirinhas.each do |carteirinha| %>
		<div class="col-md-12">
			<div style="text-align:center">
				<strong> <%= carteirinha.created_at.strftime("%d/%m/%Y") %></strong>
			</div>
			<div>
			    <div>
					 <span><strong>Valor Pago:&nbsp;</strong>R$<%=  carteirinha.valor %></span><br>
					 <span><strong>Forma de Pagamento:&nbsp;</strong><%=  carteirinha.forma_pagamento.humanize %></span><br> 
					 <span><strong>Transação:&nbsp;</strong><%=  carteirinha.transaction_id %> </span><br>
			    </div>
			    <div class="progress">
			    	<% if carteirinha.solicitacao_cancelada_ou_revogada? %>
			    		<div class="progress-bar progress-bar-danger" role="progress-bar" style="width:100%;"> <%= carteirinha.status_versao_impressa %></div>
			    	<% else %>
			    		<% carteirinha.status_take_while.each do |status| %>
				    		<div class="progress-bar progress-bar-success" role="progress-bar" style="width: 20%">
				    			<%= status.humanize %>
			    			</div>
			    		<% end %>
			    	<% end %>   	
			    </div>
			</div>
	</div>
	<% end %>
<% if @carteirinhas.empty? %>
	<%= render inline: "<div style='text-align:center'><p> Não há dados a serem mostrados </p></div>" %>
<%end%>

app/views/carteirinhas/_message.html.erb
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong>Warning!</strong> Better check yourself, you're not looking too good.
</div>

app/views/carteirinhas/consulta.html.erb
<div id="flash_message">

</div> 
<div>
   <p class="soon-med">Você produtor de eventos artísiticos-culturais e esportivos consulte aqui a autenticidade da Carteira de Identificação Estudantil.</p>                                                                                
   <div class="soon-subscribe">
      <%= form_for :carteirinha, url: consulta_carteirinha_path, method: 'post', html:{:class=>"form-inline"}, remote: true do |f| %>             
         <div class="form-group">
            <%= f.text_field :codigo_uso , :class=>"form-control", :placeholder=>"Código de uso" %>      
         </div>
         </br>
         <%= recaptcha_tags %>
         </br>
         <%= f.submit "Consultar", :class=>'btn btn-info' %>  
      <% end %>            
      <div id="carteirinha">

      </div>
   </div>                                       
</div>

app/views/carteirinhas/consulta.js.erb
<% if @carteirinha && @carteirinha.valid? %>
	$('#carteirinha').html(null);
	$('#carteirinha').html("<%= j(render @carteirinha) %>");
<% else %>
	<% flash[:alert] = "Código de Uso inválido ou Documento vencido." %>
	$('#carteirinha').html(null);
	$('#flash_message').html("<%= j(render 'layouts/messages') %>");
<% end %>

app/views/carteirinhas/new.html.erb
<h3 class="text-primary"> Carteira de Identifição Estudantil </h3>
	<%= form_for ([@estudante, @estudante.carteirinhas.build]) do |f| %>
	<div class="col-md-12">
		<div class="col-md-8">
			<%= image_tag Entidade.entidade_padrao.layout_anverso.url, :class=>'img img-responsive' if Entidade.entidade_padrao.layout_anverso %>
		</div>
		<div class="col-md-5">
			<div class="checkbox"><br>
				<p><strong>Valor:</strong>&nbsp;R$<%= @entidade.valor_carteirinha.to_f %> </p>
				<%= f.hidden_field :valor_carteirinha, :value => @entidade.valor_carteirinha.to_f %>
				<% if !@entidade.frete_carteirinha.blank? %>
					<p><strong>Frete:</strong>&nbsp;R$<%= @entidade.frete_carteirinha %> </p>
					<%= f.hidden_field :frete_carteirinha, :value => @entidade.frete_carteirinha %>
				<%end%>
				<label>
					<%= f.check_box :termos %> 
					<small style="font-size: 12px;"> Aceito os <a class="text-primary" href='#' >Termos de Serviço</a> </small>
				</label>
			</div>
			<div class="input-group" role="group">
				<span class="input-group-addon bg-success"><strong>Total R$</strong></span>
				<%= f.label :total, @entidade.valor_carteirinha.to_f+@entidade.frete_carteirinha.to_f, :id=> 'carteirinha_valor', 
							:size=>'4', :class=>'form-control' %>
				<span class="input-group-btn" id="pagar_agora">
					<%= f.submit "Pagar Agora", :class=>'btn btn-success' %>
				</span>
			</div>
		</div>
	</div>
	<%end%>
	

app/views/carteirinhas/status_versao_impressas.js.erb
$("#status-versao-impressas-select").html(null).html("<%= escape_javascript(options_for_select @statuses.map{|k,v| [v,k]}) %>");