config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  begin
    ActiveAdmin.routes(self)
  rescue Exception => e
    puts "ActiveAdmin: #{e.class}: #{e}"
  end

 
  get 'pages/home',           to:"pages#index",          as: :home
  get 'pages/meia_entrada',   to:"pages#meia_entrada",   as: :meia_entrada
  get 'pages/noticias',       to:"pages#noticias",       as: :noticias
  get 'pages/consulta',       to:"pages#consulta",       as: :consulta
  get 'pages/contato',        to:"pages#contato",        as: :contato
  get 'pages/login',          to:"pages#login",          as: :login

  resources :estudantes, only: [:show, :update] do 
    resources :carteirinhas, only: [:new, :show, :autenticacao, :create]
  end
  
  post 'estudantes/senha',   to:"estudantes#update_password", as: :alterar_password
  get 'entidades/escolaridades', to:"entidades#escolaridades"
  get 'entidades/cursos', to:"entidades#cursos"

  resources :contatos, only:[:create]

  devise_for :estudantes, path: "auth", controllers: {:omniauth_callbacks=>"estudantes/omniauth_callbacks"},
                          path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', 
                                                                confirmation: 'verification', unlock: 'unblock', 
                                                                registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :escolaridades, only: [:show] do
    resource :cursos, only: [:show]
  end

  get 'carteirinhas/status', to: "carteirinhas#status_versao_impressas"

  resources :estados, only: [:show] do
    resource :cidades, only: [:show]
  end

  get 'payment/checkout',          to:'checkout#create',        as: :checkout
  get 'payment/confirmacao',      to:'checkout#confirmacao'
  post 'payment/notifications',    to:'notifications#create'
  
  get 'carteirinhas/image', to:'carteirinhas#carteirinha_image'
  post 'carteirinhas/consulta',   to:"carteirinhas#consulta", as: :consulta_carteirinha

  get 'certificados/:chave_acesso', to:"certificados#show" # Não alterar

  resources :eventos, only: [:show]

  namespace :api, defaults:{format: :json} do
    resources :estudantes, only: [:update], param: :oauth_token do
      resources :carteirinhas, only: [:create, :show]
    end
    get 'carteirinhas',          to: 'carteirinhas#index'
    get 'sessions/new',          to: 'sessions#create'   
    get 'sessions/new/facebook', to: 'sessions#facebook'
    post 'registration',         to: 'registrations#create' 
    resources :noticias, only:[:index]

    post 'certificados/create', to:'certificados#create'  # cria certificados
  
    get 'estudantes/:id/attachments/:name', to: 'attachments#show' 
    put 'estudantes/:id/attachments/update/:name', to: 'attachments#update'
  end

  root 'pages#index'

end

app/models/contato.rb
class Contato 
	include ActiveModel::Validations
	include ActiveModel::Conversion
	extend ActiveModel::Naming

	EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

	attr_accessor :nome, :email, :assunto, :mensagem , :telefone

	validates_presence_of :nome, :email, :mensagem
	validates :nome, :length => {in: 2..50, too_short:"Máximo de 50 caracteres permitidos."}
	validates :email, :format => {:with => EMAIL_REGEX}
	validates :telefone, :length => {in: 10..11}, numericality: true
	validates :assunto, :length => {in: 2..30, too_long: "Máximo de 30 caracteres permitidos.",
									too_short: "Mínimo de 10 caracteres permitidos."}
	validates :mensagem, :length => {in: 10..750, too_long: "Máximo de 750 caracteres permitidos.",
									too_short: "Mínimo de 10 caracteres permitidos."}

	def initialize(attributes = {})
		attributes.each do |name, value|
			send("#{name}=", value)
		end
	end

	def persisted?
		false
	end
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
	def create
		@contato = Contato.new(contato_params)
		if @contato.valid?
			ContatoMailer.contato_mensagem(@contato).deliver
			flash.notice = 'Recebemos seu contato, retornaremos em breve.'
			redirect_to contato_path
		else
			flash.alert = 'Ocorreu um erro: '.concat(@contato.errors.full_messages.to_s)
			redirect_to contato_path
		end
	end

	private 
		def contato_params
			params.require(:contato).permit(:nome,:email,:assunto,
				                            :mensagem,:telefone)
		end
end

app/views/contatos/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-4 col-sm-offset-4">
		<h2>Contato </h2>
		<%= form_for :contato , url: contatos_path, html:{:class=>'form-horizontal'} do |f| %>
			<div class="form-group">
				<%= f.label :nome, :class=>'control-label' %>
				<%= f.text_field :nome, :class=>'form-control', :placeholder=>'Nome'%>
			</div>
			<div class="form-group">
				<%= f.label :email %>
				<%= f.text_field :email, :class=>'form-control', :placeholder=>'Email' %>
			</div>
			<div class="form-group">
				<%= f.label :telefone %>
				<%= f.text_field :telefone, :class=>'form-control', :placeholder=>'Telefone' %>
			</div>
			<div class="form-group">
				<%= f.label :assunto %>
				<%= f.text_field :assunto,:class=>'form-control', :placeholder=>'Assunto' %>
			</div> 
			<div class="form-group">
				<%= f.label :mensagem %>
				<%= f.text_area :mensagem,:class=>'form-control', rows: '6', :placeholder=>'Mensagem aqui'  %>
			</div>
			<div class="actions form-group">
				<%= f.submit "Enviar", :class=>'btn btn-success' %>
			</div>
		<% end %>
		</div>
	</div>
</div>