config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  begin
    ActiveAdmin.routes(self)
  rescue Exception => e
    puts "ActiveAdmin: #{e.class}: #{e}"
  end

 
  get 'pages/home',           to:"pages#index",          as: :home
  get 'pages/meia_entrada',   to:"pages#meia_entrada",   as: :meia_entrada
  get 'pages/noticias',       to:"pages#noticias",       as: :noticias
  get 'pages/consulta',       to:"pages#consulta",       as: :consulta
  get 'pages/contato',        to:"pages#contato",        as: :contato
  get 'pages/login',          to:"pages#login",          as: :login

  resources :estudantes, only: [:show, :update] do 
    resources :carteirinhas, only: [:new, :show, :autenticacao, :create]
  end
  
  post 'estudantes/senha',   to:"estudantes#update_password", as: :alterar_password
  get 'entidades/escolaridades', to:"entidades#escolaridades"
  get 'entidades/cursos', to:"entidades#cursos"

  resources :contatos, only:[:create]

  devise_for :estudantes, path: "auth", controllers: {:omniauth_callbacks=>"estudantes/omniauth_callbacks"},
                          path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', 
                                                                confirmation: 'verification', unlock: 'unblock', 
                                                                registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :escolaridades, only: [:show] do
    resource :cursos, only: [:show]
  end

  get 'carteirinhas/status', to: "carteirinhas#status_versao_impressas"

  resources :estados, only: [:show] do
    resource :cidades, only: [:show]
  end

  get 'payment/checkout',          to:'checkout#create',        as: :checkout
  get 'payment/confirmacao',      to:'checkout#confirmacao'
  post 'payment/notifications',    to:'notifications#create'
  
  get 'carteirinhas/image', to:'carteirinhas#carteirinha_image'
  post 'carteirinhas/consulta',   to:"carteirinhas#consulta", as: :consulta_carteirinha

  get 'certificados/:chave_acesso', to:"certificados#show" # Não alterar

  resources :eventos, only: [:show]

  namespace :api, defaults:{format: :json} do
    resources :estudantes, only: [:update], param: :oauth_token do
      resources :carteirinhas, only: [:create, :show]
    end
    get 'carteirinhas',          to: 'carteirinhas#index'
    get 'sessions/new',          to: 'sessions#create'   
    get 'sessions/new/facebook', to: 'sessions#facebook'
    post 'registration',         to: 'registrations#create' 
    resources :noticias, only:[:index]

    post 'certificados/create', to:'certificados#create'  # cria certificados
  
    get 'estudantes/:id/attachments/:name', to: 'attachments#show' 
    put 'estudantes/:id/attachments/update/:name', to: 'attachments#update'
  end

  root 'pages#index'

end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand pull-left" href="#">
			   <%=image_tag("logo.png", alt:"logo", :class=>'img img-responsive', :id => 'logo-image')%>
			</a>
			<button type="button" data-target="#menu-collapse" data-toggle="collapse" class="navbar-toggle pull-rigth">
				<span class="sr-only"> <%= ENV['STUDENTCASYSTEM_NOME_ENTIDADE'] %></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<div id="menu-collapse" class="collapse navbar-collapse">
	    	<ul class="nav navbar-nav navbar-right" id="top-nav">
				<li><%= link_to 'Home' , home_path %> </li>
				<li><%= link_to 'Lei da Meia Entrada' , meia_entrada_path %> </li>
				<li><%= link_to 'Notícias' , noticias_path %></li>
				<li><%= link_to 'Consulta' , consulta_path %> </li>
				<li><%= link_to 'Contato' , contato_path %></li>
				<% if estudante_signed_in? %>
					<li>
					<%= link_to estudante_path(current_estudante) do  %>
						<%= presentation_name(current_estudante.nome) %>
						<span class="glyphicon glyphicon-user text-primary"></span>
					<% end %>
					</li>
					<li><%= link_to 'Sair', destroy_estudante_session_path, :method=>:delete, class:'btn btn-info' %></li>
				<%else%>
					<li><%= link_to 'Login' , login_path, class:'btn btn-info' %> </li>
				<%end%>
			</ul>
		</div>	   
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Studentcasystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navigation' %>
	<div class="container">
		<div class="row">
			<%= render 'layouts/messages' %>
			<%= yield %>
		</div>
	</div>
</body>
</html>